site_name: rnwolf.net
site_url: https://www.rnwolf.net
site_description: 'A personal blog and portfolio of Rüdiger Wolf.'
site_author: 'rnwolf'
copyright: |
  &copy; Rüdiger Wolf 2025. All rights reserved.'
theme:
  name: material
  icon:
    logo: fontawesome/solid/lightbulb
  locale: en
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - search.highlight
    - search.suggest
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue

plugins:
  - meta
  - tags:
      tags_file: tags.md
  - caption:
      additional_identifier: ["List"]
  - social
  - search
  - inline-select-svg:
      pattern: "[.]inline[.]svg$"
  - blog:
      blog_dir: blog
      categories_allowed:
        - technology
        - health
        - performance
        - development
        - finance
        - ai
  - rss:
      pretty_print: true
      match_path: "blog/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: Europe/London
  - pagetree

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@RudigerWolf
    - icon: fontawesome/brands/github
      link: https://github.com/rnwolf
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rnwolf
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rudigerwolf/
  footer_links:
    - text: "Privacy Policy"
      href: "/privacy"
    - text: "Security Policy"
      href: "/security-policy"
    - text: "Copyright"
      href: "/copyright"
    - text: "RSS"
      href: "/feed_rss_created.xml"

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

nav:
  - index.md
  - Blog:
      - blog/index.md
      - Tags: tags.md
  - About: about.md
  - Contact: contact.md
  - Projects:
      - projects/our-planner/index.md
      - projects/pyccpm/index.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/posthog-script.js

exclude_docs: |
  !.well-known