site_name: My Docs
site_url: https://sitename.example
site_author: 'rnwolf'
copyright: |
  &copy; 2025 <a href="https://github.com/rnwolf"  target="_blank" rel="noopener">Rudiger Wolf</a>'
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue

plugins:
  - marimo
  - search
  - blog:
      blog_dir: blog
      categories_allowed:
        - category1
        - category2
  - tags:
      tags_file: tags.md
  - rss:
      pretty_print: true
      match_path: "blog/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: Europe/London

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: fontawesome/brands/github
      link: https://github.com/james-willett
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willetjames/

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - Blog:
      - blog/index.md
      - Tags: tags.md
  - About: about.md
  - Contact: contact.md
  - Projects:
      - project1.md
      - project2.md